#!/bin/sh

PWD=$(pwd)
# check if the user is indeed at root of react project
name=$1

while [[ $name == "" ]]
do 
    echo "Choose a name for your component :"
    read name
done 

if [ -d "${PWD}/src" ] 
    then echo "src exists. Files will be created with name $name."
        
    else echo "/src does not exist, check that you are in the right directory. Exiting now." 
    exit  
fi

if [ -d "${PWD}/src/components" ]
    then 
        echo "This script will create files for react component $name. Continue [y/n]?"
        read response
            if [ $response = "n" ] || [ $response = "N" ] ; 
            then exit
            fi
    else
        echo "Components directory not found. Create directory + react component $name files? [y/n] "
        read response
            if [ $response = "n" ] || [ $response = "N" ] ; 
            then exit
            fi
        mkdir ${PWD}/src/components
        
fi

mkdir ${PWD}/src/components/$name
        printf "import React from 'react';\nimport styles from './$name.module.css';\n\nconst $name = props => ();\n\nexport default $name"  > ${PWD}/src/components/$name/$name.js
        touch ${PWD}/src/components/$name/$name.module.css
        echo "Created directories and files!"
